# GENERATED by gendocs from docs/gotchas/ — do not edit
# Fuente: docs/gotchas/*.md — regenerar con `make gen-agent-docs`.
# Este archivo se hace `source` desde las guardias de scripts/testing/.
#
#   GOTCHA_IDS     todos los ids, en el orden canónico
#   ANCLAS         "término|id" de cada trap y rule (términos que un manual
#                  sembrado NO puede perder)
#   MENTIRAS       "frase|id" de cada frase de `lies:` (una entrada por frase)
#   PATTERN_CODES  "W1NN|id" de cada gotcha con pattern grep-able

GOTCHA_IDS=(
  "nested-map-from-call"
  "option-struct-multifield-link"
  "small-channel-deadlock"
  "ffi-c-int-no-sign-extend"
  "fn-callback-typed"
  "await-float-gated"
  "channel-is-map"
  "charat-returns-int"
  "enum-dot-not-colons"
  "map-literal-string-keys"
  "strings-are-bytes"
  "check-bind-return"
  "assert-aborts-process"
  "bare-return-void"
  "fork-gc-child-exec"
  "global-struct-zeroinitializer"
  "prelude-frozen-snapshot"
  "hkt-gats-parse-only"
  "implicit-monomorphization-nested"
  "and-or-short-circuit"
  "nested-arrays-work"
  "map-remove-on-field"
  "gc-exhaustion-ordered-error"
  "chr-zero-nul-byte"
  "array-elem-method-chaining"
  "closure-capture-works"
  "tcp-write-loops-until-sent"
  "udp-binary-payload-intact"
  "tls-peer-cert-introspection"
  "missing-method-compile-error"
  "repl-declared-subset"
  "bind-failure-loud"
  "file-api-names"
  "array-index-float-write"
  "sync-global-init-reliable"
)

ANCLAS=(
  "user::name|nested-map-from-call"
  "Option<Array>|option-struct-multifield-link"
  "deadlock|small-channel-deadlock"
  "sign-extend|ffi-c-int-no-sign-extend"
  "Fn(Type)|fn-callback-typed"
  "NYX1021|await-float-gated"
  "channel_new|channel-is-map"
  "charAt|charat-returns-int"
  "Shape.Circle|enum-dot-not-colons"
  "NYX0106|map-literal-string-keys"
  "BYTES|strings-are-bytes"
  "tcp_listen|check-bind-return"
  "exit(1)|assert-aborts-process"
  "\`void\`|bare-return-void"
)

MENTIRAS=(
  "map literal {} is NOT supported|map-literal-string-keys"
  "map.remove(k) on a struct field is a silent no-op|map-remove-on-field"
  "arr[i].method() causes SEGV|array-elem-method-chaining"
  "closure capture of locals is broken|closure-capture-works"
  "capture is BROKEN|closure-capture-works"
  "open_file(|file-api-names"
  "close_file(|file-api-names"
  "corrupts the value on the next read|array-index-float-write"
)

PATTERN_CODES=(
  "W104|channel-is-map"
  "W103|charat-returns-int"
  "W101|enum-dot-not-colons"
  "W102|map-literal-string-keys"
  "W107|check-bind-return"
)
