#!/usr/bin/env bash
# run_gendocs_test.sh — test de fixture del generador `compiler/gendocs.nx`.
#
# Corre `nyx_gendocs` sobre un directorio de juguete (tests/gendocs/fixture/,
# COPIADO a un tmp para no ensuciar el repo) con 2 gotchas y un doc.md con dos
# regiones, y verifica la salida REAL byte a byte: la región corta, la región
# larga con su marca [test: …], la tabla compilada, los cuatro arrays de bash,
# `--check` (verde tras regenerar, ROJO tras tocar un destino: control
# positivo) y `fixed-since`.
#
# set -u sin pipefail (regla del repo: grep -q + pipe muerde con SIGPIPE).
set -u
cd "$(dirname "$0")/../.."
ROOT="$PWD"

# build-gendocs pisa script.nx/script.ll de la raíz — sin el lock, dos runners
# simultáneos se entrelazan y el binario que se testea no es el que se compiló.
source scripts/testing/lib_testroot_lock.sh
nyx_testroot_lock_acquire

FAIL=0
ok()  { printf "  ✓ %s\n" "$1"; }
bad() { printf "  ✗ %s\n" "$1"; FAIL=$((FAIL + 1)); }

# SIEMPRE reconstruir: si sólo se construyera cuando falta, este test validaría
# un binario viejo justo después de editar compiler/gendocs.nx — que es el
# momento exacto en que hace falta que sea honesto.
if ! make -s build-gendocs >/dev/null 2>&1 || [ ! -x ./nyx_gendocs ]; then
    echo "  ✗ no se pudo construir nyx_gendocs (make build-gendocs)"
    exit 1
fi
GEN="$ROOT/nyx_gendocs"

T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT
cp -R tests/gendocs/fixture/. "$T/"
# El loader valida que el `test:` de cada gotcha exista en disco — el fixture
# cita un test real, así que se copia al tmp con su misma ruta relativa.
mkdir -p "$T/tests/ai-first"
cp tests/ai-first/01-shortcircuit.nx "$T/tests/ai-first/"

cd "$T"
export NYX_GOTCHAS_DIR=gotchas
export NYX_GENDOCS_TARGETS=doc.md
export NYX_GENDOCS_TABLE=gotchas_table.nx
export NYX_GENDOCS_BASH=gotchas_generated.sh

# ── 1. Regeneración ──────────────────────────────────────────────────────
if "$GEN" > gen.log 2>&1; then
    ok "regeneración del fixture (rc=0)"
else
    bad "regeneración falló (rc=$?): $(head -5 gen.log)"
    cd "$ROOT"; echo "  gendocs: FALLÓ"; exit 1
fi

# ── 2. Región corta (kinds=trap lang=en form=short) ──────────────────────
grep -qxF '<!-- gen:ids a-trap -->' doc.md \
    && ok "gen:ids de la región corta" \
    || bad "falta «<!-- gen:ids a-trap -->» en doc.md"
grep -qxF '1. **A trap short.**' doc.md \
    && ok "ítem 1 de la región corta = forma corta exacta" \
    || bad "la región corta no contiene «1. **A trap short.**»"
grep -q 'The long form adds this second sentence' doc.md \
    && bad "form=short filtró la forma larga a la región corta" \
    || ok "form=short recorta la forma larga"
grep -q 'b-fixed' <<< "$(sed -n '/kinds=trap lang=en/,/\/gen:gotchas/p' doc.md)" \
    && bad "la región kinds=trap incluyó un gotcha fixed" \
    || ok "kinds=trap filtra por kind"

# ── 3. Región larga (kinds=trap,fixed lang=es form=long) ─────────────────
grep -qxF '<!-- gen:ids a-trap,b-fixed -->' doc.md \
    && ok "gen:ids de la región larga (2 ids, en orden)" \
    || bad "falta «<!-- gen:ids a-trap,b-fixed -->» en doc.md"
grep -qxF '1. **Una trampa corta.** La forma larga agrega esta segunda oración sobre `foo(`. [test: 01-shortcircuit]' doc.md \
    && ok "ítem 1 largo en español + marca [test: …]" \
    || bad "el ítem 1 de la región larga no tiene el cuerpo es + marca esperados"
grep -qxF '2. **B ya está arreglado.** Antes decía `bar is broken`.' doc.md \
    && ok "ítem 2 numerado sin huecos y sin marca (test vacío)" \
    || bad "el ítem 2 de la región larga no es el esperado"

# ── 4. Prosa fuera de los marcadores intacta ─────────────────────────────
grep -qxF 'Esta línea de arriba NO se toca.' doc.md \
    && grep -qxF 'Esta línea de abajo tampoco se toca.' doc.md \
    && ok "el texto fuera de las regiones quedó intacto" \
    || bad "se tocó texto fuera de los marcadores"

# ── 5. Tabla compilada ───────────────────────────────────────────────────
head -1 gotchas_table.nx | grep -q '^// GENERATED by gendocs from docs/gotchas/ — do not edit$' \
    && ok "cabecera GENERATED en la tabla .nx" \
    || bad "gotchas_table.nx sin la cabecera GENERATED"
N_ROWS=$(grep -c 'rows.push(\[' gotchas_table.nx)
[ "$N_ROWS" = 2 ] && ok "la tabla tiene 2 filas" || bad "la tabla tiene $N_ROWS filas (esperadas 2)"
grep -q 'pub fn gotchas_table() -> Array' gotchas_table.nx \
    && grep -q 'pub fn gotcha_field(row: Array, name: String) -> String' gotchas_table.nx \
    && ok "firmas públicas de la tabla" \
    || bad "faltan las firmas gotchas_table()/gotcha_field() en la tabla"
grep -q '"a-trap", "trap", "silent-wrong", "0.29.0", "", "foo\\\\(", "W199", "foo", "", "tests/ai-first/01-shortcircuit.nx", "A trap short."' gotchas_table.nx \
    && ok "fila de a-trap con los 12 campos en orden (pattern escapado, título sin **)" \
    || bad "la fila de a-trap no tiene los 12 campos esperados"

# ── 6. Arrays de bash ────────────────────────────────────────────────────
head -1 gotchas_generated.sh | grep -q '^# GENERATED by gendocs from docs/gotchas/ — do not edit$' \
    && ok "cabecera GENERATED en los arrays de bash" \
    || bad "gotchas_generated.sh sin la cabecera GENERATED"
# shellcheck disable=SC1091
if ( set -u; . ./gotchas_generated.sh
     [ "${#GOTCHA_IDS[@]}" = 2 ] && [ "${GOTCHA_IDS[0]}" = "a-trap" ] && [ "${GOTCHA_IDS[1]}" = "b-fixed" ] \
     && [ "${#ANCLAS[@]}" = 1 ]  && [ "${ANCLAS[0]}" = "foo|a-trap" ] \
     && [ "${#MENTIRAS[@]}" = 1 ] && [ "${MENTIRAS[0]}" = "bar is broken|b-fixed" ] \
     && [ "${#PATTERN_CODES[@]}" = 1 ] && [ "${PATTERN_CODES[0]}" = "W199|a-trap" ] ); then
    ok "GOTCHA_IDS / ANCLAS / MENTIRAS / PATTERN_CODES con los valores esperados"
else
    bad "los arrays de gotchas_generated.sh no son los esperados"
    sed -n '1,40p' gotchas_generated.sh | sed 's/^/      /'
fi

# ── 7. --check verde tras regenerar (y regeneración idempotente) ─────────
cp doc.md doc.md.snap
if "$GEN" --check > check1.log 2>&1; then
    ok "--check verde tras regenerar"
else
    bad "--check rojo tras regenerar: $(cat check1.log)"
fi
"$GEN" > /dev/null 2>&1
cmp -s doc.md doc.md.snap && ok "regenerar dos veces es no-op" || bad "la segunda regeneración cambió doc.md"

# ── 8. Control positivo: --check ROJO tras tocar un destino ──────────────
sed -i 's/^1\. \*\*A trap short\.\*\*$/1. **A trap short (editado a mano).**/' doc.md
if "$GEN" --check > check2.log 2>&1; then
    bad "--check quedó VERDE con doc.md editado a mano (el instrumento no detecta nada)"
else
    grep -q '^stale: doc.md$' check2.log \
        && ok "--check rojo + «stale: doc.md» tras editar el destino" \
        || bad "--check falló pero no imprimió «stale: doc.md»: $(cat check2.log)"
fi
"$GEN" > /dev/null 2>&1   # restaurar
rm -f gotchas_table.nx
if "$GEN" --check > check3.log 2>&1; then
    bad "--check quedó VERDE con la tabla borrada"
else
    grep -q '^stale: gotchas_table.nx$' check3.log \
        && ok "--check rojo + «stale: gotchas_table.nx» si falta un generado" \
        || bad "--check no reportó la tabla faltante: $(cat check3.log)"
fi
"$GEN" > /dev/null 2>&1

# ── 9. fixed-since ───────────────────────────────────────────────────────
OUT="$("$GEN" fixed-since 0.29.0 2>&1)"
[ "$OUT" = "b-fixed: B is fixed now." ] \
    && ok "fixed-since 0.29.0 lista b-fixed con su título en inglés" \
    || bad "fixed-since 0.29.0 imprimió «$OUT»"
OUT="$("$GEN" fixed-since 0.30.0 2>&1)"
[ -z "$OUT" ] \
    && ok "fixed-since 0.30.0 no lista nada (comparación por tres enteros)" \
    || bad "fixed-since 0.30.0 imprimió «$OUT» (debería ser vacío)"
OUT="$("$GEN" fixed-since 0.9.0 2>&1)"
[ "$OUT" = "b-fixed: B is fixed now." ] \
    && ok "fixed-since 0.9.0 compara 9 < 30 como enteros, no como texto" \
    || bad "fixed-since 0.9.0 imprimió «$OUT»"

# ── 10. Un `pattern:` que no compila muere RUIDOSO en el loader ──────────
# regex_is_match no sirve para validar: ante un regcomp fallido imprime por
# stderr y devuelve 0, igual que un patrón válido que no matchea. El primitivo
# es regex_is_valid (std/regex + nyx_regex_is_valid).
cp "$ROOT/tests/gendocs/fixture/invalid/bad-pattern.md" gotchas/
if "$GEN" > badpat.log 2>&1; then
    bad "un pattern inválido ([unclosed) pasó la validación con rc=0"
else
    grep -q 'bad-pattern.md: pattern inválido: \[unclosed' badpat.log \
        && ok "un pattern que no compila falla ruidoso con archivo y patrón" \
        || bad "el loader falló pero sin el mensaje de pattern inválido: $(cat badpat.log)"
fi
rm -f gotchas/bad-pattern.md

cd "$ROOT"
echo ""
if [ "$FAIL" -gt 0 ]; then
    echo "  gendocs (fixture): FALLÓ ($FAIL problema(s))"
    exit 1
fi
echo "  gendocs (fixture): PASS"
exit 0
